server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.30.129 # 如 192.168.1.100
    port: 5672
    username: root # 对应启动容器时的 RABBITMQ_DEFAULT_USER
    password: root # 对应启动容器时的 RABBITMQ_DEFAULT_PASS
    virtual-host: /hello # 默认虚拟主机
    # 消费端核心配置（关键）
    listener:
      simple:
        acknowledge-mode: manual # 手动确认（保证消息不丢失，核心！）
        concurrency: 1 # 最小消费线程数
        max-concurrency: 5 # 最大消费线程数
        retry:
          enabled: true # 开启消费重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 1000ms # 首次重试间隔

